name: React Deployment S3 bucket

on:
  push:
    branches:
      - ci-cd-pranav

env:
  AWS_REGION: us-east-2

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: AWS
    

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }} 
        
    - name: Run script
      run: bash ./CID/deployReactS3.sh
